### ISSUE TITLE
Need Help Creating Vietnamese Font

### ISSUE THREAD

**Issue by JokerDKha** [TeamPBCN/Metroid-Samus-Returns#1]
Im very want to translation this game but i'm stuck in edit this font. Can you help me step by step how to translation this font game?
Thank you very much for hard work.

**Comment by LITTOMA** [comment]
You can use this repo to translate the game with the following steps:
1. Check out the latest commit of this repo
2. Install python dependencies:
`python -m pip install fire pygame`
3. Export text (_Assuming you're translating from Japanese_):
`python btxt.py -xb <path/to/your/extracted/romfs>/system/localization/japanese.txt -p localization\japanese.txt`
The exported txt should looks like below:
```
No.0
Label: GUI_MENU001
－－－－－－－－－－－－－－－－－－－－
＂ を押してスタート
－－－－－－－－－－－－－－－－－－－－
＂ を押してスタート
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝


No.1
Label: GUI_USEDNA_CANNOTUSE
－－－－－－－－－－－－－－－－－－－－
封印を解除するには
メトロイドDNAが必要です。
メトロイドDNAを持っていません。
－－－－－－－－－－－－－－－－－－－－
封印を解除するには
メトロイドDNAが必要です。
メ_トロイドDNAを持っていません。
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

...
```
The second part of each block is for translating. You can edit it like below:
```
No.0
Label: GUI_MENU001
－－－－－－－－－－－－－－－－－－－－
＂ を押してスタート
－－－－－－－－－－－－－－－－－－－－
This is a translated text.
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

...
```
4. After edited, use the below command to rebuild a binary txt:
`python btxt -cb japanese.txt -p localization\japanese.txt`
5. Build fonts by running `build_font.bat`

### Notes:
* Scripts in this repo only run on python 2.7

**Comment by JokerDKha** [comment]
Thank's it text is working fine.
But: Build fonts by running build_font.bat seen like not working
![image](https://user-images.githubusercontent.com/56380626/130409694-63064a62-e688-4c65-998a-2c3a91d15368.png)
im already pip install fire pygame:
![image](https://user-images.githubusercontent.com/56380626/130409956-9c5fc506-1566-4429-8896-1bf3c9fe52ad.png)

**Comment by LITTOMA** [comment]
Can you share the output of build_font.bat?

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/130410724-d8793220-0301-4e4a-a8fd-1402c5d83b9e.png)
![image](https://user-images.githubusercontent.com/56380626/130410758-5a50c870-1fa7-40a7-84cd-e8fdc04b6659.png)

**Comment by LITTOMA** [comment]
From the picture, I can see it runs at least the first 12 lines in the batch file. 
It would be better if you could share the console output of build_font.bat

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/130412830-d4fe5875-ec73-4eac-bab8-37c3006d1832.png)
![image](https://user-images.githubusercontent.com/56380626/130412854-283464b7-40b4-4ec4-95f4-9eeb330bb17d.png)

**Comment by LITTOMA** [comment]
Seems like you have 32bit python installed in your system. Can you retry with 64bit python?

**Comment by JokerDKha** [comment]
im try python 64bit now:
and now it error like this:
![Uploading image.png…]()

**Comment by LITTOMA** [comment]
Oh, I made a mistake in the file paths.
Updated build_font.bat now. Please try again.

**Comment by JokerDKha** [comment]
now build_font.bat working but after im but in a game like this.
![image](https://user-images.githubusercontent.com/56380626/130418506-4e607f70-ab32-4536-a78e-939759705512.png)

**Comment by JokerDKha** [comment]
Updated a Font Build Not Working.
[build.zip](https://github.com/TeamPBCN/Metroid-Samus-Returns/files/7032191/build.zip)

**Comment by LITTOMA** [comment]
I used the wrong path splitter in the inner paths of *.mfnt files.
It should be fixed now. Have a try :)

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/130549854-bba60fc3-3b47-400c-9fbd-a50e9c0759a7.png)
Thanks for your help so much <3 every thing is worrking perfect now.
